---
ID: "c3d4e5f6-a7b8-9012-cdef-123456789013"
Parent: "c3d4e5f6-a7b8-9012-cdef-123456789012"
Template: "c3d4e5f6-a7b8-9012-cdef-123456789012"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Property/PropertyGrid/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T120000Z
