---
ID: "a7b8c9d0-e1f2-3456-0123-456789012357"
Parent: "a7b8c9d0-e1f2-3456-0123-456789012356"
Template: "a7b8c9d0-e1f2-3456-0123-456789012356"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Forms/PropertyEnquiryForm/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T120000Z
