---
ID: "b8901234-ef01-2345-8901-234abcdef057"
Parent: "b8901234-ef01-2345-8901-234abcdef056"
Template: "b8901234-ef01-2345-8901-234abcdef056"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Community/CommunityShowcase Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{e5f6a7b8-c9d0-1234-ef01-234567890134}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T000000Z
