---
ID: "d4e5f6a7-b8c9-0123-def0-123456789024"
Parent: "d4e5f6a7-b8c9-0123-def0-123456789023"
Template: "d4e5f6a7-b8c9-0123-def0-123456789023"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Community/CommunityCard/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T120000Z
