---
ID: "d4567890-abcd-ef01-4567-890abcdef013"
Parent: "d4567890-abcd-ef01-4567-890abcdef012"
Template: "d4567890-abcd-ef01-4567-890abcdef012"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Property/PropertyCard Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{b2c3d4e5-f6a7-8901-bcde-f12345678901}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T000000Z
