---
ID: "d0123456-0123-4567-0123-456abcdef079"
Parent: "d0123456-0123-4567-0123-456abcdef078"
Template: "d0123456-0123-4567-0123-456abcdef078"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Global Elements/Header Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{a2a2b2c2-d2e2-f202-0202-020202020202}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T000000Z
