---
ID: "f2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a8c"
Parent: "f2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a8b"
Template: "f2f3a4b5-c6d7-8e9f-0a1b-2c3d4e5f6a8b"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Testimonials/TestimonialCard/__Standard Values"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/speech_bubble.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T120000Z
