---
ID: "a7890123-def0-1234-7890-123abcdef046"
Parent: "a7890123-def0-1234-7890-123abcdef045"
Template: "a7890123-def0-1234-7890-123abcdef045"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Community/CommunityCard Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{d4e5f6a7-b8c9-0123-def0-123456789012}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T000000Z
