---
ID: "h3a3b3c3-d3e3-f303-0303-030303030304"
Parent: "h3a3b3c3-d3e3-f303-0303-030303030303"
Template: "h3a3b3c3-d3e3-f303-0303-030303030303"
Path: "/sitecore/templates/Project/kit-next-realstate/Components/Global Elements/SitecorePropertiesFooter/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251206T000000Z
